### ISSUE TITLE
Wonderful works. Only a slight question of the model prediction.

### ISSUE THREAD

**Issue by liyucheng09** [tuhinjubcse/model-in-the-loop-fig-lang#1]
I understand a prompt consists of promise and hypothesis is feed into T5 encoder.
But how the T5 decoder works?

How did you extract predicted_label from the text produced by T5 decoder?
Will there always be predicted_labels in the generated test?
What if the label is missing in the output text?

**Comment by tuhinjubcse** [comment]
Yes 
{"translation": {"en1": "Does the sentence \"My mom can be a little too persistent about things she doesn't know much about.\" entail or contradict the sentence \"I love how my mom is always sticking her nose and being too curious for her own good when it comes to things she doesn't know about\"? Please answer between \"Entails\" or \"Contradicts\" and explain your decision in a sentence.", "en2": "Contradicts. People usually don't love it when their mothers act this way because they can be overbearing and not give them the privacy they need."}}


The output will be Label. Explanation
